In [1]:
import pandas as pd

In [2]:
dataframe = pd.read_csv('cepes.csv', low_memory=False)

In [3]:
dataframe

,idEstado,estado,idMunicipio,municipio,ciudad,zona,cp,asentamiento,tipo
0,1,Aguascalientes,1,Aguascalientes,Aguascalientes,Urbano,20000,Zona Centro,Colonia
1,1,Aguascalientes,1,Aguascalientes,Aguascalientes,Urbano,20010,Colinas del Rio,Fraccionamiento
2,1,Aguascalientes,1,Aguascalientes,Aguascalientes,Urbano,20010,Las Brisas,Fraccionamiento
3,1,Aguascalientes,1,Aguascalientes,Aguascalientes,Urbano,20010,Olivares Santana,Colonia
4,1,Aguascalientes,1,Aguascalientes,Aguascalientes,Urbano,20010,Ramon Romo Franco,Fraccionamiento
...,...,...,...,...,...,...,...,...,...
145903,32,Zacatecas,56,Zacatecas,NaN,Rural,98183,Garcia de La Cadena (el Visitador),Poblado comunal
145904,32,Zacatecas,56,Zacatecas,NaN,Rural,98184,Las Chilitas,Poblado comunal
145905,32,Zacatecas,56,Zacatecas,NaN,Rural,98185,La Soledad (la Chole),Poblado comunal
145906,32,Zacatecas,56,Zacatecas,NaN,Rural,98186,Benito Juárez (san Cayetano),Poblado comunal
145907,32,Zacatecas,56,Zacatecas,NaN,Rural,98186,Miguel Hidalgo (san Miguel),Poblado comunal

In [4]:
dataframe.drop_duplicates()

,idEstado,estado,idMunicipio,municipio,ciudad,zona,cp,asentamiento,tipo
0,1,Aguascalientes,1,Aguascalientes,Aguascalientes,Urbano,20000,Zona Centro,Colonia
1,1,Aguascalientes,1,Aguascalientes,Aguascalientes,Urbano,20010,Colinas del Rio,Fraccionamiento
2,1,Aguascalientes,1,Aguascalientes,Aguascalientes,Urbano,20010,Las Brisas,Fraccionamiento
3,1,Aguascalientes,1,Aguascalientes,Aguascalientes,Urbano,20010,Olivares Santana,Colonia
4,1,Aguascalientes,1,Aguascalientes,Aguascalientes,Urbano,20010,Ramon Romo Franco,Fraccionamiento
...,...,...,...,...,...,...,...,...,...
145903,32,Zacatecas,56,Zacatecas,NaN,Rural,98183,Garcia de La Cadena (el Visitador),Poblado comunal
145904,32,Zacatecas,56,Zacatecas,NaN,Rural,98184,Las Chilitas,Poblado comunal
145905,32,Zacatecas,56,Zacatecas,NaN,Rural,98185,La Soledad (la Chole),Poblado comunal
145906,32,Zacatecas,56,Zacatecas,NaN,Rural,98186,Benito Juárez (san Cayetano),Poblado comunal
145907,32,Zacatecas,56,Zacatecas,NaN,Rural,98186,Miguel Hidalgo (san Miguel),Poblado comunal

In [5]:
list(dataframe.columns)

['idEstado',
 'estado',
 'idMunicipio',
 'municipio',
 'ciudad',
 'zona',
 'cp',
 'asentamiento',
 'tipo']

In [6]:
cdmx_dataframe = dataframe.loc[dataframe['ciudad'] == 'Ciudad de México']
cdmx_dataframe

,idEstado,estado,idMunicipio,municipio,ciudad,zona,cp,asentamiento,tipo
23071,9,Ciudad de México,10,Álvaro Obregón,Ciudad de México,Urbano,1000,San Ángel,Colonia
23072,9,Ciudad de México,10,Álvaro Obregón,Ciudad de México,Urbano,1010,Los Alpes,Colonia
23073,9,Ciudad de México,10,Álvaro Obregón,Ciudad de México,Urbano,1020,Guadalupe Inn,Colonia
23074,9,Ciudad de México,10,Álvaro Obregón,Ciudad de México,Urbano,1029,INFONAVIT,Gran usuario
23075,9,Ciudad de México,10,Álvaro Obregón,Ciudad de México,Urbano,1030,Axotla,Pueblo
...,...,...,...,...,...,...,...,...,...
25093,9,Ciudad de México,13,Xochimilco,Ciudad de México,Urbano,16889,Villa San Isidro,Campamento
25094,9,Ciudad de México,13,Xochimilco,Ciudad de México,Urbano,16900,San Francisco Tlalnepantla,Pueblo
25095,9,Ciudad de México,13,Xochimilco,Ciudad de México,Urbano,16908,Los Capulines,Campamento
25096,9,Ciudad de México,13,Xochimilco,Ciudad de México,Urbano,16909,Club Monte Sur,Campamento
25097,9,Ciudad de México,13,Xochimilco,Ciudad de México,Urbano,16910,Pedregal de San Francisco,Campamento

In [7]:
gpe_df = cdmx_dataframe.loc[dataframe['cp'] == 7840]
gpe_df

,idEstado,estado,idMunicipio,municipio,ciudad,zona,cp,asentamiento,tipo
23968,9,Ciudad de México,5,Gustavo A. Madero,Ciudad de México,Urbano,7840,7 de Noviembre,Colonia
23969,9,Ciudad de México,5,Gustavo A. Madero,Ciudad de México,Urbano,7840,Guadalupe Tepeyac,Colonia

In [8]:
clean_df = cdmx_dataframe.drop(columns = ['idEstado', 'idMunicipio', 'ciudad', 'zona', 'tipo'])
clean_df

                 estado       municipio     cp                asentamiento
23071  Ciudad de México  Álvaro Obregón   1000                   San Ángel
23072  Ciudad de México  Álvaro Obregón   1010                   Los Alpes
23073  Ciudad de México  Álvaro Obregón   1020               Guadalupe Inn
23074  Ciudad de México  Álvaro Obregón   1029                   INFONAVIT
23075  Ciudad de México  Álvaro Obregón   1030                      Axotla
...                 ...             ...    ...                         ...
25093  Ciudad de México      Xochimilco  16889            Villa San Isidro
25094  Ciudad de México      Xochimilco  16900  San Francisco Tlalnepantla
25095  Ciudad de México      Xochimilco  16908               Los Capulines
25096  Ciudad de México      Xochimilco  16909              Club Monte Sur
25097  Ciudad de México      Xochimilco  16910   Pedregal de San Francisco

[2027 rows x 4 columns]

In [9]:
clean_df.columns = ['estado', 'delegación', 'cp', 'colonia']
clean_df

                 estado      delegación     cp                     colonia
23071  Ciudad de México  Álvaro Obregón   1000                   San Ángel
23072  Ciudad de México  Álvaro Obregón   1010                   Los Alpes
23073  Ciudad de México  Álvaro Obregón   1020               Guadalupe Inn
23074  Ciudad de México  Álvaro Obregón   1029                   INFONAVIT
23075  Ciudad de México  Álvaro Obregón   1030                      Axotla
...                 ...             ...    ...                         ...
25093  Ciudad de México      Xochimilco  16889            Villa San Isidro
25094  Ciudad de México      Xochimilco  16900  San Francisco Tlalnepantla
25095  Ciudad de México      Xochimilco  16908               Los Capulines
25096  Ciudad de México      Xochimilco  16909              Club Monte Sur
25097  Ciudad de México      Xochimilco  16910   Pedregal de San Francisco

[2027 rows x 4 columns]

In [10]:
clean_df.dtypes

estado        object
delegación    object
cp             int64
colonia       object
dtype: object

In [11]:
clean_df['cp'] = clean_df['cp'].astype(str)
clean_df.dtypes

estado        object
delegación    object
cp            object
colonia       object
dtype: object

In [12]:
clean_df['cp']

23071     1000
23072     1010
23073     1020
23074     1029
23075     1030
         ...
25093    16889
25094    16900
25095    16908
25096    16909
25097    16910
Name: cp, Length: 2027, dtype: object

In [13]:
clean_df['count'] = clean_df['cp'].str.len()
clean_df

,estado,delegación,cp,colonia,count
23071,Ciudad de México,Álvaro Obregón,1000,San Ángel,4
23072,Ciudad de México,Álvaro Obregón,1010,Los Alpes,4
23073,Ciudad de México,Álvaro Obregón,1020,Guadalupe Inn,4
23074,Ciudad de México,Álvaro Obregón,1029,INFONAVIT,4
23075,Ciudad de México,Álvaro Obregón,1030,Axotla,4
...,...,...,...,...,...
25093,Ciudad de México,Xochimilco,16889,Villa San Isidro,5
25094,Ciudad de México,Xochimilco,16900,San Francisco Tlalnepantla,5
25095,Ciudad de México,Xochimilco,16908,Los Capulines,5
25096,Ciudad de México,Xochimilco,16909,Club Monte Sur,5
25097,Ciudad de México,Xochimilco,16910,Pedregal de San Francisco,5

In [14]:
cut_df = clean_df[clean_df['count'] == 5]
cut_df

,estado,delegación,cp,colonia,count
24380,Ciudad de México,La Magdalena Contreras,10000,Lomas Quebradas,5
24381,Ciudad de México,La Magdalena Contreras,10010,La Malinche,5
24382,Ciudad de México,La Magdalena Contreras,10010,San Bartolo Ameyalco,5
24383,Ciudad de México,La Magdalena Contreras,10020,Cuauhtémoc,5
24384,Ciudad de México,La Magdalena Contreras,10100,Unidad Independencia IMSS,5
...,...,...,...,...,...
25093,Ciudad de México,Xochimilco,16889,Villa San Isidro,5
25094,Ciudad de México,Xochimilco,16900,San Francisco Tlalnepantla,5
25095,Ciudad de México,Xochimilco,16908,Los Capulines,5
25096,Ciudad de México,Xochimilco,16909,Club Monte Sur,5
25097,Ciudad de México,Xochimilco,16910,Pedregal de San Francisco,5

In [15]:
cut_df.drop(columns = 'count')

,estado,delegación,cp,colonia
24380,Ciudad de México,La Magdalena Contreras,10000,Lomas Quebradas
24381,Ciudad de México,La Magdalena Contreras,10010,La Malinche
24382,Ciudad de México,La Magdalena Contreras,10010,San Bartolo Ameyalco
24383,Ciudad de México,La Magdalena Contreras,10020,Cuauhtémoc
24384,Ciudad de México,La Magdalena Contreras,10100,Unidad Independencia IMSS
...,...,...,...,...
25093,Ciudad de México,Xochimilco,16889,Villa San Isidro
25094,Ciudad de México,Xochimilco,16900,San Francisco Tlalnepantla
25095,Ciudad de México,Xochimilco,16908,Los Capulines
25096,Ciudad de México,Xochimilco,16909,Club Monte Sur
25097,Ciudad de México,Xochimilco,16910,Pedregal de San Francisco

In [16]:
cut_df = cut_df[['cp', 'colonia', 'delegación', 'estado']]
cut_df

,cp,colonia,delegación,estado
24380,10000,Lomas Quebradas,La Magdalena Contreras,Ciudad de México
24381,10010,La Malinche,La Magdalena Contreras,Ciudad de México
24382,10010,San Bartolo Ameyalco,La Magdalena Contreras,Ciudad de México
24383,10020,Cuauhtémoc,La Magdalena Contreras,Ciudad de México
24384,10100,Unidad Independencia IMSS,La Magdalena Contreras,Ciudad de México
...,...,...,...,...
25093,16889,Villa San Isidro,Xochimilco,Ciudad de México
25094,16900,San Francisco Tlalnepantla,Xochimilco,Ciudad de México
25095,16908,Los Capulines,Xochimilco,Ciudad de México
25096,16909,Club Monte Sur,Xochimilco,Ciudad de México
25097,16910,Pedregal de San Francisco,Xochimilco,Ciudad de México

In [17]:
short_cp = clean_df[clean_df['count'] == 4]
short_cp

                 estado      delegación    cp               colonia  count
23071  Ciudad de México  Álvaro Obregón  1000             San Ángel      4
23072  Ciudad de México  Álvaro Obregón  1010             Los Alpes      4
23073  Ciudad de México  Álvaro Obregón  1020         Guadalupe Inn      4
23074  Ciudad de México  Álvaro Obregón  1029             INFONAVIT      4
23075  Ciudad de México  Álvaro Obregón  1030                Axotla      4
...                 ...             ...   ...                   ...    ...
24375  Ciudad de México      Iztapalapa  9960  Rinconada del Molino      4
24376  Ciudad de México      Iztapalapa  9960                USCOVI      4
24377  Ciudad de México      Iztapalapa  9969               Cananea      4
24378  Ciudad de México      Iztapalapa  9970  Valle de San Lorenzo      4
24379  Ciudad de México      Iztapalapa  9979         Carmen Serdán      4

[1309 rows x 5 columns]

In [18]:
short_cp['cod_post'] = '0' + short_cp['cp'].astype(str)
short_cp

/var/folders/n9/b6fgc87j7_352bt5wgvjmfnm0000gn/T/ipykernel_42524/561224526.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  short_cp['cod_post'] = '0' + short_cp['cp'].astype(str)

,estado,delegación,cp,colonia,count,cod_post
23071,Ciudad de México,Álvaro Obregón,1000,San Ángel,4,01000
23072,Ciudad de México,Álvaro Obregón,1010,Los Alpes,4,01010
23073,Ciudad de México,Álvaro Obregón,1020,Guadalupe Inn,4,01020
23074,Ciudad de México,Álvaro Obregón,1029,INFONAVIT,4,01029
23075,Ciudad de México,Álvaro Obregón,1030,Axotla,4,01030
...,...,...,...,...,...,...
24375,Ciudad de México,Iztapalapa,9960,Rinconada del Molino,4,09960
24376,Ciudad de México,Iztapalapa,9960,USCOVI,4,09960
24377,Ciudad de México,Iztapalapa,9969,Cananea,4,09969
24378,Ciudad de México,Iztapalapa,9970,Valle de San Lorenzo,4,09970
24379,Ciudad de México,Iztapalapa,9979,Carmen Serdán,4,09979

In [19]:
short_cp = short_cp.drop(columns = ['cp', 'count'])
short_cp

                 estado      delegación               colonia cod_post
23071  Ciudad de México  Álvaro Obregón             San Ángel    01000
23072  Ciudad de México  Álvaro Obregón             Los Alpes    01010
23073  Ciudad de México  Álvaro Obregón         Guadalupe Inn    01020
23074  Ciudad de México  Álvaro Obregón             INFONAVIT    01029
23075  Ciudad de México  Álvaro Obregón                Axotla    01030
...                 ...             ...                   ...      ...
24375  Ciudad de México      Iztapalapa  Rinconada del Molino    09960
24376  Ciudad de México      Iztapalapa                USCOVI    09960
24377  Ciudad de México      Iztapalapa               Cananea    09969
24378  Ciudad de México      Iztapalapa  Valle de San Lorenzo    09970
24379  Ciudad de México      Iztapalapa         Carmen Serdán    09979

[1309 rows x 4 columns]

In [20]:
short_cp = short_cp[['cod_post', 'colonia', 'delegación','estado']]
short_cp

      cod_post               colonia      delegación            estado
23071    01000             San Ángel  Álvaro Obregón  Ciudad de México
23072    01010             Los Alpes  Álvaro Obregón  Ciudad de México
23073    01020         Guadalupe Inn  Álvaro Obregón  Ciudad de México
23074    01029             INFONAVIT  Álvaro Obregón  Ciudad de México
23075    01030                Axotla  Álvaro Obregón  Ciudad de México
...        ...                   ...             ...               ...
24375    09960  Rinconada del Molino      Iztapalapa  Ciudad de México
24376    09960                USCOVI      Iztapalapa  Ciudad de México
24377    09969               Cananea      Iztapalapa  Ciudad de México
24378    09970  Valle de San Lorenzo      Iztapalapa  Ciudad de México
24379    09979         Carmen Serdán      Iztapalapa  Ciudad de México

[1309 rows x 4 columns]

In [21]:
short_cp.columns = ['cp', 'colonia', 'delegación','estado']
short_cp

          cp               colonia      delegación            estado
23071  01000             San Ángel  Álvaro Obregón  Ciudad de México
23072  01010             Los Alpes  Álvaro Obregón  Ciudad de México
23073  01020         Guadalupe Inn  Álvaro Obregón  Ciudad de México
23074  01029             INFONAVIT  Álvaro Obregón  Ciudad de México
23075  01030                Axotla  Álvaro Obregón  Ciudad de México
...      ...                   ...             ...               ...
24375  09960  Rinconada del Molino      Iztapalapa  Ciudad de México
24376  09960                USCOVI      Iztapalapa  Ciudad de México
24377  09969               Cananea      Iztapalapa  Ciudad de México
24378  09970  Valle de San Lorenzo      Iztapalapa  Ciudad de México
24379  09979         Carmen Serdán      Iztapalapa  Ciudad de México

[1309 rows x 4 columns]

In [22]:
clean_df = pd.concat([cut_df, short_cp])

In [23]:
clean_df

,cp,colonia,delegación,estado
24380,10000,Lomas Quebradas,La Magdalena Contreras,Ciudad de México
24381,10010,La Malinche,La Magdalena Contreras,Ciudad de México
24382,10010,San Bartolo Ameyalco,La Magdalena Contreras,Ciudad de México
24383,10020,Cuauhtémoc,La Magdalena Contreras,Ciudad de México
24384,10100,Unidad Independencia IMSS,La Magdalena Contreras,Ciudad de México
...,...,...,...,...
24375,09960,Rinconada del Molino,Iztapalapa,Ciudad de México
24376,09960,USCOVI,Iztapalapa,Ciudad de México
24377,09969,Cananea,Iztapalapa,Ciudad de México
24378,09970,Valle de San Lorenzo,Iztapalapa,Ciudad de México
24379,09979,Carmen Serdán,Iztapalapa,Ciudad de México